############# Chinese navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "关于"
url = "/about"
weight = 2

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1
